# Generated by Django 2.1.1 on 2018-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181212_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stylist',
            new_name='is_publisher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clearance',
        ),
        migrations.AddField(
            model_name='user',
            name='is_definer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
